CREATE TABLE utenti (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL,
  cognome TEXT NOT NULL,
  data_di_nascita DATE NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  ruolo TEXT NOT NULL CHECK(ruolo IN ('admin', 'paziente'))
);

CREATE TABLE piano_alimentare (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  utente_id INTEGER NOT NULL,
  titolo TEXT NOT NULL,
  descrizione TEXT,
  contenuto TEXT NOT NULL,
  data_creazione DATE NOT NULL,
  FOREIGN KEY(utente_id) REFERENCES utenti(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE misurazioni (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  utente_id INTEGER NOT NULL,
  misura REAL,
  data DATE NOT NULL,
  FOREIGN KEY(utente_id) REFERENCES utenti(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE recensioni (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  utente_id INTEGER NOT NULL,
  commento TEXT NOT NULL,
  valutazione INTEGER NOT NULL DEFAULT 5 CHECK(valutazione BETWEEN 1 AND 5),
  data_creazione DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(utente_id) REFERENCES utenti(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE richieste_contatto (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL,
  email TEXT NOT NULL,
  messaggio TEXT NOT NULL,
  data_creazione DATETIME DEFAULT CURRENT_TIMESTAMP
);
